User.all.each {|u| u.destroy }
Post.all.each {|p| p.destroy }

u1 = User.create!(:first_name => 'ryan', :last_name => 'ferretti', :username => 'ryan', :email => 'ryan@gmail.com', :password => "ahhh", :password_confirmation => 'ahhh')

p1 = Post.create!(:user_id => u1.id, :post_type => :normal, :title => "Why non-profit pricing?", :tag_list => "awesome, slick, hefty",:body => "Over the past six years weve had hundreds of requests for non-profit discounts. They come from non-profits of all sizes. Some are huge multinational charities, some are small local volunteer organizations, others are somewhere in the middle. Just like there are small businesses, medium sized businesses, and large businesses, there are small, medium, and large non-profits. The fundamental difference between a for-profit business and a non-profit business is the profit. For-profits are allowed to realize a profit, non-profits arent. Non-profits can generate a profit Ð called a surplus Ð but they have to reinvest it back into the organization. For-profits can take the profit and distribute it to their shareholders, owners, or anyone else theyd like. Thats the key difference. There are some other differences too. Some might say that non-profits do good, while for-profits do business, but I dont believe that 1. matters, or 2. suggests that for-profits dont do good.")
p2 = Post.create!(:user_id => u1.id, :post_type => :normal, :title => "How do I learn to program?", :tag_list => "hefty", :body => "t took me some twenty-plus years to really learn how to program. It wasnt for a lack of trying either, it was just that I was trying the wrong way. I tried to learn to program by following tutorials that created programs I didnt have the slightest interest in keeping. I was trying to learn for the sake of learning. Now Im sure that works for some people. Intellectually curious for the sake of it. I envy you. But thats not how it worked for me and I know thats not how it works for a lot of other people. What made it click for me was programming in anger. Programming because I needed to. Programming because I gave a damn about what I was writing and I wanted it done sooner rather than later.")
p3 = Post.create!(:user_id => u1.id, :post_type => :normal, :title => "Worrying about the wrong things.", :tag_list => "awesome, hefty",:body => "Starting a new company is full of chaos and uncertainty. There are plenty of very reasonable things to worry about, like, will we make any money? Do we have the right product? How do we find any customers? But these are often not the things starters choose to worry about. Instead, they worry about things they should be so lucky to encounter. Will my software platform scale if I get 10,000 customers per day? Do we have the right strategic plan for the next three years? What should our stock option plan look like so itll cope with 100+ people? To make something of yourself, you can only worry about so much. Theres a certain set of worry slots available and if you fill them with all these possibly-maybe concerns, there wont be any left for things thatll matter tomorrow.")
p4 = Post.create!(:user_id => u1.id, :post_type => :normal, :title => "Loading spinner animation using CSS and WebKit", :tag_list => "slick, dope",:body => "When it comes to acquisitions, there are only two things worth buying: products and customers. When you buy either, youre buying a solid stream of revenue. All you have to do is not fuck it up. Thats harder than you think, but the good news is that there is room for error. Fuck it up a little and only a few will leave. You still have the entrenched rest to make the purchase pay. Not so with ideas or talent. These are the purchases of aspiration: Imagine if we took that scrappy idea with those underpaid, hungry champions, and we gave them all the resources in the world. They could paint all the colors of the rainbow and still have pixie dust left to spare!")

p1.comments.create!(:author => "Ryan", :body => "seriously, that was EXACTLY what I needed to read right now. I just became your lifetime fan. seriously")
p1.comments.create!(:author => "Jim", :body => "I think there are probably counterexamples in that vein, though I agree with your point with respect to large companies.")
p1.comments.create!(:author => "John", :body => "As for hiring talentÉwell you can get them on payrole sure, but getting optimal performance and creativity generally isnt achieved via monetary incentives.")
p1.comments.create!(:author => "Mark", :body => "Necessity is the mother of invention , whilst may be a cliche is something I try and live by.")

p2.comments.create!(:author => "Julie", :body => "seriously, that was EXACTLY what I needed to read right now. I just became your lifetime fan. seriously")
p2.comments.create!(:author => "Pete", :body => "I think there are probably counterexamples in that vein, though I agree with your point with respect to large companies.")

p4.comments.create!(:author => "Emily", :body => "seriously, that was EXACTLY what I needed to read right now. I just became your lifetime fan. seriously")

puts "# of Users created: #{User.all.count}"
puts "# of Posts created: #{Post.all.count}"
puts "# of Comments created: #{Comment.all.count}"